<?php 
    include_once('Conexao.php');
    include_once('Helper.php');
    include_once('Usuario.php');
    include_once('Medicos.php');
    include_once('Captacao.php');
    include_once('Setor.php');
    include_once('Chamados.php');
    include_once('Cargo.php');
    include_once('Log.php');
    include_once('Compras_Categorias.php');
    include_once('Compras_Fornecedores.php');
    include_once('Compras_Notas.php');
    include_once('Compras_Pedidos.php');
    include_once('Projetos.php');
    include_once('Financeiro_Campanhas.php');
    include_once('Financeiro_Boletos.php');
    include_once('Conversas.php');
    include_once('Mensagens.php');
?>