<?php 
    include_once('Conexao.php');
    include_once('Helper.php');
    include_once('Usuario.php');
    include_once('Setor.php');
    include_once('Cargo.php');
    include_once('Log.php');
    include_once('Compras_Categorias.php');
    include_once('Compras_Fornecedores.php');
    include_once('Compras_Notas.php');
?>